# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.S')

LIBS        = ["libmotion_det.a"]
LIBS				+= ["libjpeg.a"]

libpath = [cwd]

group = DefineGroup('motion_det', src,depend = [''], LIBS=LIBS, LIBPATH = libpath)

Return('group')
